name: Add Issues and PRs to RNBO Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to RNBO Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/bynarlogic/projects/${{ secrets.PROJECT_NUMBER }}
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: bug
          label-operator: NOT

